// ============================================================================
// Standalone PROOF for the deterministic world core (the rollback keystone).
//   Run:  node --experimental-strip-types src/sim/world/prove.ts
// ============================================================================
//
// This proves the three properties the entire rollback model depends on. If any
// fails, rollback would silently desync — so we prove them in isolation, before
// building netcode on top (DECISIONS-LOG build philosophy).
//
//   PROOF 1 — DETERMINISM. The same initial state + same input stream, simulated
//             twice, yields an identical per-tick hash sequence. (No hidden
//             nondeterminism: no Date/random/float drift/iteration-order leak.)
//
//   PROOF 2 — SAVE/RESTORE EXACTNESS. Snapshot at tick T, run to T+M, restore to
//             T, run again to T+M → identical hash. (clone/restoreInto are exact.)
//
//   PROOF 3 — ROLLBACK EQUIVALENCE (the real one). Run a reference simulation
//             recording every tick's hash. Then run a second "live" simulation
//             that REPEATEDLY rolls back a random number of ticks and re-simulates
//             forward (the rollback hot path), and assert every re-derived tick's
//             hash equals the reference. This is a local stand-in for the
//             "Two-Browser Grab Proof" minus cross-engine + the (not-yet-built)
//             grab/throw verbs — it validates the resim machinery itself, already
//             exercising a carried (slaved) body.
//
// The input stream is generated by a seeded integer PRNG so the "game" is real and
// input-driven (determinism would be trivial for a static scene), yet reproducible.
// ============================================================================

import { createWorld, spawnBody, BodyFlag, MassClass, NO_ENTITY, type WorldState } from './state.ts';
import { hashWorld } from './hash.ts';
import { clone, restoreInto, statesEqual } from './snapshot.ts';
import { step, TICK_HZ } from './step.ts';
import { type PlayerInput, Button, MOVE_Q } from './input.ts';
import { fromInt, fromFloatConst } from '../fixed/fixed.ts';

// ---- seeded integer PRNG (test input only; not the sim) ---------------------
function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const NUM_PLAYERS = 4;
const TICKS = 1800; // 30 s at 60 Hz

/** Build the initial scene: some players, an anchor, some throwables. Deterministic. */
function makeScene(): { world: WorldState; playerIds: number[]; anchorId: number } {
  const w = createWorld(64);
  const playerIds: number[] = [];
  for (let i = 0; i < NUM_PLAYERS; i++) {
    const id = spawnBody(w, {
      px: fromInt(i * 2 - 3),
      py: fromInt(5),
      pz: fromInt(0),
      radius: fromFloatConst(0.4),
      halfHeight: fromFloatConst(0.9),
      massClass: MassClass.Player,
      flags: BodyFlag.Player,
    });
    playerIds.push(id);
  }
  const anchorId = spawnBody(w, {
    px: fromInt(0),
    py: fromInt(5),
    pz: fromInt(2),
    radius: fromFloatConst(0.5),
    halfHeight: fromFloatConst(1.0),
    massClass: MassClass.Anchor,
    flags: BodyFlag.Player | BodyFlag.Anchor,
  });
  // a few throwable objects
  for (let i = 0; i < 6; i++) {
    spawnBody(w, {
      px: fromInt(i - 3),
      py: fromInt(3),
      pz: fromInt(-2),
      radius: fromFloatConst(0.3),
      halfHeight: fromFloatConst(0.3),
      massClass: i % 2 === 0 ? MassClass.Light : MassClass.Heavy,
      flags: BodyFlag.Throwable,
    });
  }
  // Slave one throwable to player 0 to exercise the carry transform (SYSTEM 5).
  const carried = NUM_PLAYERS + 1; // first throwable id
  w.grabbedBy[carried] = playerIds[0]!;
  w.flags[carried] = (w.flags[carried]! | BodyFlag.NoGravity) & 0xffff;
  w.holding[playerIds[0]!] = carried;
  void NO_ENTITY;
  return { world: w, playerIds, anchorId };
}

/** Deterministic per-tick inputs for all players, from a seeded PRNG. */
function makeInputStream(seed: number, players: number[], ticks: number, capacity: number): PlayerInput[][] {
  const rnd = mulberry32(seed);
  const stream: PlayerInput[][] = [];
  // persistent per-player intent that changes occasionally (more realistic motion)
  const cur: PlayerInput[] = players.map(() => ({ moveX: 0, moveZ: 0, aim: 0, buttons: 0, grabTarget: -1 }));
  for (let t = 0; t < ticks; t++) {
    const frame: PlayerInput[] = new Array(capacity);
    for (let pi = 0; pi < players.length; pi++) {
      if (rnd() < 0.08) {
        // occasionally pick a new intent
        cur[pi] = {
          moveX: Math.floor((rnd() * 2 - 1) * MOVE_Q),
          moveZ: Math.floor((rnd() * 2 - 1) * MOVE_Q),
          aim: Math.floor((rnd() * 2 - 1) * 205887), // ~[-PI,PI] raw
          buttons: rnd() < 0.1 ? Button.Jump : 0,
          grabTarget: -1,
        };
      }
      frame[players[pi]!] = cur[pi]!;
    }
    stream.push(frame);
  }
  return stream;
}

/** Simulate `ticks` from a fresh scene, returning the per-tick hash array. */
function runReference(stream: PlayerInput[][]): { hashes: number[]; final: WorldState } {
  const { world } = makeScene();
  const hashes: number[] = [hashWorld(world)];
  for (let t = 0; t < stream.length; t++) {
    step(world, stream[t]!);
    hashes.push(hashWorld(world));
  }
  return { hashes, final: world };
}

let failures = 0;
const log = (s: string) => console.log(s);

// ---------------------------------------------------------------------------
log('----------------------------------------------------------------');
log('ASCENT world core — STANDALONE PROOF (determinism / save-restore / rollback)');
log('----------------------------------------------------------------');

const SEED = 0x1234abcd;
const scene0 = makeScene();
const stream = makeInputStream(SEED, scene0.playerIds, TICKS, scene0.world.capacity);

// PROOF 1 — determinism across two independent runs.
const ref = runReference(stream);
const ref2 = runReference(stream);
let p1 = ref.hashes.length === ref2.hashes.length;
if (p1) for (let i = 0; i < ref.hashes.length; i++) if (ref.hashes[i] !== ref2.hashes[i]) { p1 = false; break; }
log(`PROOF 1 determinism (${TICKS} ticks, ${NUM_PLAYERS} players): ${p1 ? 'PASS' : 'FAIL'}`);
if (!p1) failures++;

// PROOF 2 — save at T, run to T+M, restore to T, run to T+M, compare hashes.
{
  const { world } = makeScene();
  const T = 600, M = 300;
  for (let t = 0; t < T; t++) step(world, stream[t]!);
  const snap = clone(world);
  const hashesA: number[] = [];
  for (let t = T; t < T + M; t++) { step(world, stream[t]!); hashesA.push(hashWorld(world)); }
  // restore and replay
  const work = makeScene().world;
  restoreInto(work, snap);
  const restoredExact = statesEqual(work, snap);
  const hashesB: number[] = [];
  for (let t = T; t < T + M; t++) { step(work, stream[t]!); hashesB.push(hashWorld(work)); }
  let p2 = restoredExact && hashesA.length === hashesB.length;
  if (p2) for (let i = 0; i < hashesA.length; i++) if (hashesA[i] !== hashesB[i]) { p2 = false; break; }
  log(`PROOF 2 save/restore exactness (restore@${T}, replay ${M}): ${p2 ? 'PASS' : 'FAIL'}${restoredExact ? '' : ' [restore not byte-exact]'}`);
  if (!p2) failures++;
}

// PROOF 3 — rollback torture: many forced rollbacks must reproduce the reference.
{
  const rnd = mulberry32(0xfeed);
  const work = makeScene().world;
  // ring of saved frames keyed by tick (simple Map keyed by tick for the test only;
  // not on a determinism-sensitive path — we read by explicit tick key).
  const frames = new Map<number, WorldState>();
  frames.set(0, clone(work));
  let mismatches = 0;
  let rollbacks = 0;
  let t = 0;
  while (t < TICKS) {
    step(work, stream[t]!);
    t++;
    if (hashWorld(work) !== ref.hashes[t]) mismatches++;
    frames.set(t, clone(work));
    // occasionally force a rollback of up to 8 ticks and resimulate forward
    if (t > 10 && rnd() < 0.25) {
      const back = 1 + Math.floor(rnd() * 8);
      const target = t - back;
      const snap = frames.get(target);
      if (snap) {
        restoreInto(work, snap);
        rollbacks++;
        // resim forward to t, checking each re-derived hash against the reference
        for (let tt = target; tt < t; tt++) {
          step(work, stream[tt]!);
          if (hashWorld(work) !== ref.hashes[tt + 1]) mismatches++;
        }
      }
    }
    // prune old frames to keep the test's memory bounded (keep last ~32)
    if (t > 32) frames.delete(t - 33);
  }
  const p3 = mismatches === 0;
  log(`PROOF 3 rollback equivalence (${rollbacks} forced rollbacks): ${p3 ? 'PASS' : 'FAIL'} (${mismatches} hash mismatches)`);
  if (!p3) failures++;
}

log('----------------------------------------------------------------');
if (failures === 0) {
  log('RESULT: PASS — the world core is deterministic, save/restore is exact,');
  log('        and forced rollbacks reproduce the reference exactly.');
  (globalThis as { process?: { exit(code: number): void } }).process?.exit(0);
} else {
  log(`RESULT: FAIL — ${failures} property(ies) failed.`);
  (globalThis as { process?: { exit(code: number): void } }).process?.exit(1);
}
